export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const ADD_ENTRY = 'ADD_ENTRY';
export const FETCH_ALL_PUBLIC_ENTRIES = 'FETCH_ALL_PUBLIC_ENTRIES';
export const FETCH_ENTRY_DETAILS = 'FETCH_ENTRY_DETAILS';
export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_PRIVATE_ENTRIES = 'FETCH_USER_PRIVATE_ENTRIES';
